yatube/about/urls.py
from . import views

from django.urls import path


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin

from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

from django.conf import settings

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название'
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Слаг'
    )
    description = models.TextField('Описание')

    class Meta:
        default_related_name = 'groups'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True,
        help_text='Добавьте картинку',
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:settings.LIMIT_TEXT]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        blank=True,
        null=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        blank=True,
        null=True
    )
    text = models.TextField(
        verbose_name='Комментарий',
        help_text='Введите комментарий'
    )
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name='Пользователь',
        on_delete=models.CASCADE,
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='following',
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_follow'
            ),
        ]

    def __str__(self):
        return f'Подписка {self.user} на {self.author}'

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст комментария'
        }
        help_text = {
            'text': 'Напишите комментарий'
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404


from .models import Group, Follow, Post, User
from .forms import CommentForm, PostForm
from .utils import paginations


def index(request):
    post_list = Post.objects.all()
    page_obj = paginations(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_obj = paginations(request, post_list)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    page_obj = paginations(request, post_list)
    context = {
        'author': author,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    user = post.author
    count = Post.objects.filter(author_id=user).all().count()
    form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'count': count,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    post = form.save(commit=False)
    if form.is_valid():
        post.author = request.user
        form.save()
        return redirect('posts:profile', username=request.user)
    return render(request, 'posts/post_create.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/post_create.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
    }
    return render(request, 'posts/post_create.html', context)


@login_required
def follow_index(request):
    posts = Post.objects.filter(
        author__following__user=request.user
    )
    page_obj = paginations(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(
            user=request.user,
            author=author
        )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(
        user=request.user,
        author=author
    ).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/follow.html
{% extends 'base.html' %}

{% load thumbnail %}

{% block title %}
  Записи избранных авторов
{% endblock %}

{% block content %}
{% load thumbnail %}
{% load cache %}
{% cache 20 index_page page_obj.number %}
<div class="container py-5">
  <h1>Записи избранных авторов</h1>

  {% for post in page_obj %}  
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>      
    <p>{{ post.text|linebreaksbr }}</p>
    <p><a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a></p>
    {% if post.group %} 
    <a href="{% url 'posts:group_posts' post.group.slug %}"> 
      все записи группы</a>
    {% endif %}  
  </article>
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% endcache %}
</div>
  {% include 'includes/paginator.html' %} 
{% endblock %} 

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% load thumbnail %}

{% block title %}Записи группы {{ group.title }}{% endblock %}

{% block content %}
<div class="container py-5">
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}      
    <p>{{ post.text|linebreaksbr }}</p>
    <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a> 
  </article>
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% load thumbnail %}

{% block title %}
  Последние обновления на сайте
{% endblock %}

{% block content %}
{% load thumbnail %}
{% load cache %}
{% cache 20 index_page page_obj.number %}
{% include 'includes/switcher.html' %}
<div class="container py-5">
  <h1>Последние обновления на сайте</h1>

  {% for post in page_obj %}  
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>      
    <p>{{ post.text|linebreaksbr }}</p>
    <p><a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a></p>
    {% if post.group %} 
    <a href="{% url 'posts:group_posts' post.group.slug %}"> 
      все записи группы</a>
    {% endif %}  
  </article>
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% endcache %}
</div>
  {% include 'includes/paginator.html' %} 
{% endblock %} 

yatube/templates/posts/post_create.html
{% extends 'base.html' %}

{% block title %}
  {% if post_id %}Редактировать запись{% else %}Добавить запись{% endif %}
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if post_id %}
            Редактировать запись
          {% else %}
            Добавить запись
          {% endif %}
        </div>
        <div class="card-body">
        {% load user_filters %}
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}

        <form method="post" action="
          {% if post_id %}
            {% url 'posts:post_edit' post_id %}
          {% else %}
            {% url 'posts:post_create' %}
          {% endif %}
        "
        >
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          
          {% for field in form %}
            <div class="form-group row my-3 p-3">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help.text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
          {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}Сохранить{% else %}Добавить{% endif %}  
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}Пост {{ post.text|truncatechars:30 }} {% endblock %}


{% block content %}
{% load thumbnail %}
{% load user_filters %}
    <div class="container py-5">
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
            {% if post.group %}  
              <li class="list-group-item">
                Группа: {{ post.group.title }}
                  <a href="{% url 'posts:group_list' post.group.slug %}">
                    все записи группы
                  </a>
              </li>
            {% endif %}            
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора: {{ author.posts.count }}
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text|linebreaksbr }}</p>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
          {% if request.user == post.author %}
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
              редактировать запись
            </a>
          {% endif %}
        </article>
        {% if user.is_authenticated %}
          <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
              <form method="post" action="{% url 'posts:add_comment' post.id %}">
                {% csrf_token %}      
                <div class="form-group mb-2">
                  {{ form.text|addclass:"form-control" }}
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
              </form>
            </div>
          </div>
        {% endif %}

        {% for comment in comments %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                  {{ comment.author.username }}
                </a>
              </h5>
              <p>
                {{ comment.text|linebreaks }}
              </p>
            </div>
          </div>
        {% endfor %} 
    </div>
  </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% load thumbnail %}

{% block title %}Профайл пользователя {{ author.get_full_name }}{% endblock %}

{% block content %}
      <div class="mb-5">       
        <h1>Все посты пользователя {{ author.get_full_name }} </h1>
        <h3>Всего постов: {{ author.posts.count }} </h3>
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
        {% endif %}
        {% for post in page_obj %}
        <article>
          <ul>
            {% if post.group %}
              <li>
                Группа: {{ post.group.title }}
                <a href="{% url 'posts:group_list' post.group.slug %}">
                  все записи группы</a>
              </li>
            {% endif %}   
            <li>
              Автор: {{ author.get_full_name }}
              <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
          </ul>
          <p>{{ post.text|linebreaksbr }} </p>
          <a href="{% url 'posts:post_edit' post.id %}">подробная информация </a>
        </article>
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}        
      {% include 'includes/paginator.html' %}
    </div>
{% endblock %} 